data_files:
    - storage: public
      url: path_a_data

bigquery:
  project_id: 'project-id'
  credentials: 'config/cred_path'

xgboost:
  expvars_names:
    - 'listar_variables_explicativas'

  expvars_df: 'root_a_df_con_variables_explicativas'
  terrenos_root: 'root_a_modelo_entrenado_oferta_terrenos'
  deptos_root: 'root_a_modelo_entrenado_oferta_deptos'
